name: deploy-auth

on:
  push:
    branches:
      - main
    paths:
      - "auth/**"

jobs:
  deploy-auth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code or latest repo
        uses: actions/checkout@v3

      - name: docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin

      - name: build auth image
        run: cd auth/ && docker build -t hilare/auth .

      - name: push auth image to docker hub
        run: docker push hilare/auth