name: deploy-client

on:
  push:
    paths:
      - "client/**"
    branches:
      - "main"

jobs:
  deploy-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code or latest repo
        uses: actions/checkout@v3

      - name: create env file
        run: |
          cd client
          touch .env
          echo HOST_URL=${{ secrets.HOST_URL }} >> .env

      - name: docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: build client image
        run: cd client/ && docker build -t hilare/client .

      - name: push client image to docker hub
        run: docker push hilare/client

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig for kubernetes cluster
        run: doctl kubernetes cluster kubeconfig save remixticket

      - run: kubectl rollout restart deployment client-depl