name: deploy-tickets

on:
  push:
    paths:
      - "tickets/**"
    branches:
      - "main"

jobs:
  deploy-tickets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code or latest repo
        uses: actions/checkout@v3

      - name: docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: build tickets image
        run: cd tickets/ && docker build -t hilare/tickets .

      - name: push tickets image to docker hub
        run: docker push hilare/tickets

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig for kubernetes cluster
        run: doctl kubernetes cluster kubeconfig save iticketing

      - run: kubectl rollout restart deployment tickets-depl