name: deploy-auth

on:
  push:
    paths:
      - "auth/**"
    branches:
      - "main"

jobs:
  deploy-auth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code or latest repo
        uses: actions/checkout@v3

      - name: docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: build auth image
        run: cd auth/ && docker build -t hilare/auth .

      - name: push auth image to docker hub
        run: docker push hilare/auth