name: deploy-auth

on:
  push:
    paths:
      - "auth/**"
    branches:
      - "main"

jobs:
  deploy-auth:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code or latest repo
        uses: actions/checkout@v3

      - name: docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: build auth image
        run: cd auth/ && docker build -t hilare/auth .

      - name: push auth image to docker hub
        run: docker push hilare/auth

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig for kubernetes cluster
        run: doctl kubernetes cluster kubeconfig save itickets

      - run: kubectl rollout restart deployment auth-depl