name: deploy-orders

on:
  push:
    paths:
      - "orders/**"
    branches:
      - "main"

jobs:
  deploy-orders:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code or latest repo
        uses: actions/checkout@v3

      - name: docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: build orders image
        run: cd orders/ && docker build -t hilare/orders .

      - name: push orders image to docker hub
        run: docker push hilare/orders

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig for kubernetes cluster
        run: doctl kubernetes cluster kubeconfig save itickets

      - run: kubectl rollout restart deployment orders-depl