name: deploy-payments

on:
  push:
    paths:
      - "payments/**"
    branches:
      - "main"

jobs:
  deploy-payments:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code or latest repo
        uses: actions/checkout@v3

      - name: docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: build payments image
        run: cd payments/ && docker build -t hilare/payments .

      - name: push payments image to docker hub
        run: docker push hilare/payments

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig for kubernetes cluster
        run: doctl kubernetes cluster kubeconfig save remixticket

      - run: kubectl rollout restart deployment payments-depl