name: test tickets

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "tickets/**"
  push:
    branches: [ "main" ]
    paths:
      - "tickets/**"

jobs:
  test-tickets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code or latest repo
        uses: actions/checkout@v3

      - name: start tests
        run: cd tickets/ && npm install && npm run test:ci